// This file is generated by the FlutterFire CLI.
// Run `flutterfire configure` to regenerate it with your actual Firebase credentials.
// See the README setup instructions for details.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace all placeholder values below by running `flutterfire configure`

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMcIfB5Z7EA1s3V3FfVomkKIlT_ilAcXE',
    appId: '1:942774640408:web:e304813d560d996ffb086d',
    messagingSenderId: '942774640408',
    projectId: 'ficus-base',
    authDomain: 'ficus-base.firebaseapp.com',
    databaseURL: 'https://ficus-base-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ficus-base.firebasestorage.app',
    measurementId: 'G-RJE6BD57FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB0_C8xKenB0jWkjQ0OWvWDoUhotp3r88',
    appId: '1:942774640408:android:719aeb654b83d31dfb086d',
    messagingSenderId: '942774640408',
    projectId: 'ficus-base',
    databaseURL: 'https://ficus-base-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ficus-base.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-iHW3qUqMbBTPyFnENL42BqE7DUa_mBo',
    appId: '1:942774640408:ios:ab8623643cc017eefb086d',
    messagingSenderId: '942774640408',
    projectId: 'ficus-base',
    databaseURL: 'https://ficus-base-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ficus-base.firebasestorage.app',
    iosBundleId: 'com.hmsnetworks.ficusApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'ficus-base',
    databaseURL:
        'https://ficus-base-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.hmsnetworks.ficusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'ficus-base',
    databaseURL:
        'https://ficus-base-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );
}
